### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by ezdux**
Code cleanup and formatting. For the formatting, I used `rustfmt`. For the cleanup, I do it by hand. Also, you might wanna check `lib.rs` line [13](https://github.com/ezdux/todo/blob/master/src/lib.rs#L13). Basically, instead of making the `TODO` file in the current directory, it creates it in `$HOME/TODO`

### CODE REVIEW

**Comment by grtcdr** [comment]
Hi, I'm not really sure cluttering `$HOME` is a great idea. This is what `$XDG_DATA_HOME` is for, e.g. read todos from `$XDG_DATA_HOME/todo/todos`

**Comment by ezdux** [comment]
In that case, you need to do some checks for Windows users since `$XDG_DATA_HOME` is not set on Windows

**Comment by ezdux** [comment]
> 
> 
> Hi, I'm not really sure cluttering `$HOME` is a great idea. This is what `$XDG_DATA_HOME` is for, e.g. read todos from `$XDG_DATA_HOME/todo/todos`

Fixed 👍

**Comment by grtcdr** [comment]
Great stuff! :) Thank you.

**Comment by grtcdr** [comment]
Just so you know: `env::var_os("XDG_DATA_HOME")` or any other XDG base directory variables can sometimes return `None`.

So you should default to `$HOME/.local/share` as per [XDG's Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

**Comment by ezdux** [comment]
> Just so you know: `env::var_os("XDG_DATA_HOME")` or any other XDG base directory variables can sometimes return `None` (as they might not be set in the first place).
> 
> So you should default to `$HOME/.local/share` as per [XDG's Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

About that, I think this should work
```rs
 let mut home = env::var_os("XDG_DATA_HOME").unwrap_or(env::var_os("HOME").unwrap());

if cfg!(windows) {
    home = env::var_os("USERPROFILE").unwrap();
}
```
If somehow this won't work, I'll change it later

**Comment by grtcdr** [comment]
On my machine for example: `env::var_os("XDG_DATA_HOME")` is going to fail, so the program is going to look for the todos in `env::var_os("HOME")`, instead it should look for it in `$HOME/.local/share`.

**Pull request merged**
