### PR TITLE
Rewrote it for fun:)

### PR DESCRIPTION
**Pull request by OST-Gh**
Rewrote the source code to be (in my opinion) more efficient.

### CODE REVIEW

**Comment by sioodmy** [comment]
damn
that looks good
I never thought someone would actually care about my rust hello world project 
imma check it out

**Comment by OST-Gh** [comment]
Oops

**Comment by OST-Gh** [comment]
so, i've accidentally removed my fork, because i thought that i could without affecting this pull-request.
turns out it does; the more you know

**Comment by OST-Gh** [comment]
i've got motivation again, let's see what we can do

**Pull request closed without merging**
